- name: Add survey host dynamically
  hosts: all
  gather_facts: false
  tasks:
    - add_host:
        name: "{{ target_host }}"
        groups: dynamic

- name: Run tasks on dynamic host
  hosts: dynamic
  become: true
  tasks:
    - file:
        path: /etc/siva
        state: directory
