- name: Dispatcher Playbook
  hosts: all
  gather_facts: false
  tasks:
    - name: Include RPC playbook
      import_playbook: rpc.yml
      when: target_playbook == "rpc"

    - name: Include SSHD playbook
      import_playbook: Find_world-writable_files_and_set_sticky_bit.yml
      when: target_playbook == "WWF"
