- name: Build dynamic inventory and include only the chosen playbook
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Include the selected task file
      include_tasks: "{{ target_playbook }}.yml"
      run_once: true

- name: Execute tasks on {{ target_host }}
  hosts: dynamic_targets
  become: true
  gather_facts: no
  tasks:
    - name: Run selected tasks
      import_tasks: "{{ target_playbook }}.yml"
